### ISSUE TITLE
pessoas colectivas e isenção

### ISSUE THREAD

**Issue by marado** [DiogoConstantino/PL246#14]
As Pessoas Colectivas não estão isentas - porque nunca podem ser, logo à partida, objecto de taxação.
Pessoas Colectivas não têm o direito à cópia privada, logo não a podem fazer, logo não podem causar dano por elas, logo não há lugar a compensação.
Uma compensação só poderia - logo à partida - atingir as pessoas individuais (que têm direito à excepção), pelo que se tal compensação for estipulada sob a forma de taxa, então tal taxa só pode ser aplicada sobre o PVP a pessoas singulares, e nunca sobre o PVP a pessoas colectivas.

**Comment by marado** [comment]
On Dec 22, 2014 2:41 PM, "Diogo Constantino" <notifications@github.com>
wrote:
>
> Eu já tinha previsto isenção em modificação anterior (#8), mas já alterei
ainda mais para clarificar que simplesmente não devem pagamento por causa
do CDADC.

Em vez de negativo ("não devem pagamento das...") o pagamento devia ser
positivo ("o pagamento é devido às pessoas singulares...").

**Comment by DiogoConstantino** [comment]
Já mudei isso, vê lá se concordas com a redacção
