### ISSUE TITLE
Rever lista de dispositivos taxaveis

### ISSUE THREAD

**Issue by marado** [DiogoConstantino/PL246#15]
A Directiva dita, tal como foi afirmado no caso Padawan, que aqui cito, que a “aplicação da taxa a equipamentos reservados a usos diferentes da realização de cópias para uso privado não é conforme com a Directiva”. Isto está, inclusivé, vertido no articulado da Proposta de Lei, ao dizer que “todos e quaisquer aparelhos que permitam a fixação de obras como finalidade única ou principal”. No entanto, a Proposta de Lei pretende taxar dispositivos como Set-Top-Boxes, TV’s, PC’s, telemóveis, tablets, e outros que, claramente, não têm como seu propósito único nem primeiro a realização de cópias para uso privado. Assim sendo, um grande leque dos equipamentos que aqui se pretende taxar não podem, segundo a directiva, ser taxados com esta finalidade.

**Comment by DiogoConstantino** [comment]
Os PC, não são taxaveis... Está logo no Artigo 1º.
Quanto às Set-Top-Boxes... Tenho dúvidas.

Na minha opinião os telemóveis e tablets não devem ser taxáveis. Mas duvido que isso passe... Contudo não me custa propor.

Há uma questão ambigua que são os dispositivos hibridos. Há tablets que são convertiveis em PC e PC que podem ser utilizados como tablet. Para além disso vários fabricantes de software e hardware desenvolvem dispositivos e software de forma a tornar a experiência de utilização, numa experiência única, quer através dos dispositivos hibridos quer através do software com interfaces unificadas.

Vou tentar rever isso ainda hoje.

**Comment by marado** [comment]
As STB não podem ser taxadas por vários motivos. Podemos logo começar pelo facto do dono da STB ser a operadora e não o end user, mas, mesmo que assim não fosse, a operadora paga licenciamento para poder providenciar o serviço de gravação, pelo que não se trata de uma cópia não autorizada pelos detentores de direitos - logo não é cópia privada.

Um dispositivo híbrido é um computador, IMHO, mas isso torna-se irrelevante quando tanto os PCs como as tablets não são taxáveis.

Não é uma questão de isto "passar ou não", é uma questão de cumprir a directiva...

**Comment by DiogoConstantino** [comment]
Feito, vê se concordas.

**Comment by DiogoConstantino** [comment]
Eu acho que os dispositivos hibridos também são computadores pessoais, porque também são utilizados como tal... Bons exemplo são os produtos mais recentes da mircrosoft, ou o asus transformer.
