### ISSUE TITLE
Criar branch AEL

### ISSUE THREAD

**Issue by marado** [DiogoConstantino/PL246#16]
A AEL também apresentou um conjunto de alterações[1], em formato "PL alterada". 
Seria interessante criar um branch a partir do texto inicial, e com um commit por cada uma das alterações da AEL (e commit message a justificação apresentada pela AEL). Assim, depois seria mais fácil fazer merge dos dois branches e termos a certeza que todas as alerações devidas se encontram no documento final.

[1] http://ensinolivre.pt/propostas-de-altera%C3%A7%C3%A3o-%C3%A0-proposta-de-lei-n%C2%BA-246xii-c%C3%B3pia-privada-pl118

**Comment by DiogoConstantino** [comment]
Estava a pensar no mesmo, mas ainda não tive sequer tempo para ler as propostas da AEL.

**Comment by DiogoConstantino** [comment]
Já fiz um trabalho inicial de compatibilização com a proposta da AEL... A proposta da AEL não impõe a obrigação de haver estudos, nem remove a protecção legal ao DRM, por isso tem alguns pressupostos que não são iguais aos pressupostos que temos nesta propota, contudo não deixa de ser possível haver uma maior compatibilidade.
Notóriamente não coloquei os valores da tabela a 0, mas passaram a ser valores quase simbólicos.

**Comment by marado** [comment]
Para referência: commit a2ee2e684f6e210e4442ae07f9801acb0259d511 (aparentemente não há branch, apenas esse commit)

**Comment by DiogoConstantino** [comment]
Fiz o merge antes de fazer o push
