### ISSUE TITLE
Factor software

### ISSUE THREAD

**Issue by DiogoConstantino** [DiogoConstantino/PL246#9]
O espaço utilizado pelo software no armazenamento dos dispositivos. Quer para o armazenamento próprio, quer em ficheiros temporários, "cache", bases de dados locais e swap de memória feita pelo sistema operativo...

**Comment by marado** [comment]
Nem de propósito: 
http://www.publico.pt/tecnologia/noticia/apple-processada-por-sistema-operativo-ocupar-ate-231-de-aparelhos-com-16-gb-1681008

De qualquer forma, não me parece que caiba no articulado da lei este tipo de coisas -- talvez no preâmbulo? A Lei define aquilo que é cobrado, esse é o tipo de texto que caberia numa directiva... mas suponho que também possa estar presente no preâmbulo, de certa forma como justificação do cálculo para os valores depois apresentados no texto.

**Comment by marado** [comment]
Proponho que este item seja deixado para depois da resolução do #15 , visto que aquele irá eliminar (pelo menos parcialmente) o trabalho a ter aqui.

**Comment by DiogoConstantino** [comment]
Acho que devemos incluir as duas opções, porque assim permite o caminho de uma proposta ser recusada e não ser a outra.

**Comment by marado** [comment]
*sigh*... 
Pode ser feito, mas isto pode chegar a um ponto muito ridículo muito rapidamente.

Todo este exercício é um "como a PL deveria ser se por acaso houvesse prejuízo económico de valor consideravel", mas agora cria-se um branch que é o "...e ainda caso a directiva não dissesse <aquilo que está no #15 >". Depois cria-se mais uma excepção, e outra, e outra... até onde?

**Comment by DiogoConstantino** [comment]
trabalho inicial em 77da0b7270
